### ISSUE TITLE
Registro de Faltas

### ISSUE THREAD

**Issue by maiarasousa** [maiarasousa/ppads-project#15]
Realizar o caso de uso com detalhamento , seguindo os seguintes requisitos:

Nome:
Resumo: 
Pré-condições:.
Pós-condições:
Fluxo Principal:
Fluxo Alternativo:

**Comment by Su1q2w3e** [comment]
Nome do caso de uso: Realizar chamada

Resumo: o professor realiza essa operação todos os dias em dois momentos: no início das aulas do dia e logo após o retorno do intervalo.

Pré-condições:
1.	O sistema de registro de presença dos alunos está funcionando corretamente.
2.	O professor está autenticado no sistema.

Pós-condições:

1.	Os registros de presença dos alunos são atualizados conforme a chamada realizada pelo professor.
Fluxo principal: 
1.	O caso de uso começa quando o professor seleciona a opção de "Realizar chamada" no sistema.
2.	O sistema exibe a lista de turmas e horários disponíveis para a chamada.
3.	O professor seleciona a turma e o momento da chamada (início das aulas do dia ou após o retorno do intervalo).
4.	O sistema exibe a lista de alunos matriculados na turma selecionada.
5.	O professor marca a presença ou ausência de cada aluno presente na sala.
6.	O sistema registra as informações de presença e atualiza o banco de dados.
7.	O caso de uso termina.

Fluxo Alternativo - Chamada Cancelada:

No passo 1 do fluxo principal, quando o professor seleciona a opção de "Realizar chamada".
Antes de exibir a lista de turmas e horários disponíveis, o sistema verifica se há algum motivo para cancelar a chamada, como uma emergência ou interrupção inesperada.
Se a chamada for cancelada:
a. O sistema exibe uma mensagem informando ao professor sobre o cancelamento da chamada e o motivo.
b. O sistema oferece opções adicionais, como remarcar a chamada para outro horário ou registrar a razão para o cancelamento.
O caso de uso termina.
Este fluxo alternativo aborda a possibilidade de cancelamento da chamada antes mesmo de iniciar o processo de seleção de turmas e horários, permitindo ao professor tomar as devidas providências caso a chamada não possa ser realizada conforme o planejado.
