### ISSUE TITLE
Gerar Relatório de Faltas

### ISSUE THREAD

**Issue by maiarasousa** [maiarasousa/ppads-project#16]
Realizar o caso de uso com detalhamento , seguindo os seguintes requisitos:

Nome:
Resumo: 
Pré-condições:.
Pós-condições:
Fluxo Principal:
Fluxo Alternativo:

**Comment by Pedrinsanchez** [comment]
Nome do caso de uso:  Gerar relatório de faltas

Resumo: o professor ao gerar relatórios de faltas todas as informações relacionadas ao aluno devem estar agrupadas por data, ano do ensino, turma, professor disciplina.

Pré-condições:

1.	Existem registros de presença dos alunos armazenados no sistema.
2.	O professor está autenticado no sistema.
Pós-condições:
1.	Um relatório detalhado de faltas é gerado com as informações relacionadas aos alunos agrupadas por data, ano do ensino, turma e disciplina do professor.

Fluxo principal:

1.	O caso de uso começa quando o professor acessa a opção de "Gerar relatório de faltas" no sistema.
2.	O sistema exibe as opções de filtragem para o relatório, como período de datas, ano do ensino, turma e disciplina.
3.	O professor seleciona os critérios desejados para o relatório.
4.	O sistema busca os registros de presença dos alunos de acordo com os critérios selecionados.
5.	O sistema agrupa as informações dos alunos por data, ano do ensino, turma e disciplina do professor.
6.	O sistema gera o relatório de faltas com base nas informações agrupadas.
7.	O relatório é exibido para o professor, que pode visualizá-lo e, se necessário, exportá-lo em formato desejado (por exemplo, PDF, Excel).
8.	O caso de uso termina.
Fluxo Alternativo - Falha na Geração do Relatório:

No passo 6 do fluxo principal, após o sistema tentar gerar o relatório de faltas.
O sistema verifica se ocorreu uma falha na geração do relatório.
Se a geração do relatório falhar:
a. O sistema registra o erro no sistema de log para fins de rastreamento e auditoria.
b. O sistema exibe uma mensagem de erro para o usuário, informando sobre a falha na geração do relatório e oferecendo opções de resolução.
c. O usuário pode optar por tentar gerar o relatório novamente ou entrar em contato com o suporte técnico para assistência adicional.
Dependendo da ação tomada pelo usuário, o caso de uso pode ser retomado a partir do passo 2 do fluxo principal (se o usuário optar por tentar novamente) ou ser encerrado (se o usuário optar por entrar em contato com o suporte técnico ou realizar outra ação).
