### ISSUE TITLE
Notificações de Faltas Excessivas

### ISSUE THREAD

**Issue by maiarasousa** [maiarasousa/ppads-project#17]
Realizar o caso de uso com detalhamento , seguindo os seguintes requisitos:

Nome:
Resumo: 
Pré-condições:.
Pós-condições:
Fluxo Principal:
Fluxo Alternativo:

**Comment by Moqueve** [comment]
Nome do caso de uso:  Emitir notificação de faltas

Descrição: o sistema deve enviar notificações por e-mail aos pais ou responsáveis em caso de faltas excessivas, ele deve identificar alunos com porcentagem de comparecimento às aulas abaixo de 80%.

Pré-condições:
1.	O sistema possui informações atualizadas sobre os alunos e suas respectivas faltas.
2.	Os endereços de e-mail dos pais ou responsáveis pelos alunos estão cadastrados no sistema.

Pós-condições:
1.	Notificações por e-mail são enviadas aos pais ou responsáveis dos alunos que possuem uma porcentagem de comparecimento às aulas abaixo de 80%.

Fluxo principal:
1.	O caso de uso começa quando o sistema inicia o processo de verificação das faltas dos alunos.
2.	O sistema calcula a porcentagem de comparecimento às aulas de cada aluno.
3.	O sistema identifica os alunos cuja porcentagem de comparecimento está abaixo de 80%.
4.	Para cada aluno identificado, o sistema busca o endereço de e-mail do seu responsável cadastrado no sistema.
5.	O sistema gera uma notificação por e-mail contendo informações sobre as faltas do aluno e solicitação de ação por parte do responsável.
6.	O sistema envia as notificações por e-mail para os responsáveis pelos alunos identificados.
7.	O sistema registra o envio das notificações no histórico do aluno.
8.	O caso de uso termina.

Fluxo Alternativo - Falha no Envio de E-mail:
1.	No passo 6 do fluxo principal, após o sistema tentar enviar a notificação por e-mail para o responsável do aluno.
2.	O sistema verifica se houve uma falha no envio do e-mail.
3.	Se o envio do e-mail falhar: a. O sistema registra o erro de envio de e-mail no histórico do aluno. 
b. O sistema tenta enviar o e-mail novamente, até um número máximo de tentativas (por exemplo, três tentativas). 
c. Se todas as tentativas de envio falharem, o sistema registra o problema e marca o aluno para uma revisão manual pelo pessoal responsável.
