### ISSUE TITLE
Diagrama de caso de uso

### ISSUE THREAD

**Issue by Susane-Souza** [maiarasousa/ppads-project#20]

**Comment by Su1q2w3e** [comment]
[Diagrama do Sistema de presenças.pdf](https://github.com/maiarasousa/ppads-project/files/14361479/Diagrama.do.Sistema.de.presencas.pdf)

**Comment by Susane-Souza** [comment]
https://lucid.app/lucidchart/abadb932-b77c-40f7-a123-b51e462f922d/edit?viewport_loc=-741%2C-360%2C1997%2C829%2C0_0&invitationId=inv_6f705927-61d7-4642-94b9-7fb036e5ce22
