### ISSUE TITLE
Armazenamento de Dados dos Alunos

### ISSUE THREAD

**Issue by Susane-Souza** [maiarasousa/ppads-project#21]

**Comment by Su1q2w3e** [comment]
Nome do caso de uso:  Armazenar dados dos alunos

Descrição: o professor ao registrar os dados da chamada, todas as informações relacionadas ao aluno devem ser salvas e armazenadas de forma segura.

Pré-condições:
1.	O sistema de registro de presença dos alunos está funcionando corretamente.
2.	O professor está autenticado no sistema.

Pós-condições:
1.	As informações dos alunos são armazenadas de forma segura no banco de dados do sistema.

Fluxo principal:
1.	O caso de uso começa quando o professor finaliza a realização da chamada.
2.	O sistema captura as informações de presença e ausência dos alunos registradas pelo professor.
3.	Para cada aluno presente na sala, o sistema armazena suas informações, como nome, número de identificação, turma, horário da aula, data, etc.
4.	O sistema verifica se o aluno já possui informações registradas anteriormente. Se sim, atualiza os dados existentes; se não, cria um novo registro para o aluno.
5.	Todas as informações são armazenadas de forma segura no banco de dados do sistema.
6.	O caso de uso termina.



Fluxo Alternativo - Falha no Armazenamento dos Dados:

No passo 5 do fluxo principal, após o professor marcar a presença ou ausência de cada aluno e o sistema tentar armazenar as informações.
O sistema verifica se ocorreu uma falha no armazenamento dos dados.
Se o armazenamento dos dados falhar:
a. O sistema registra o erro no sistema de log para fins de rastreamento e auditoria.
b. O sistema exibe uma mensagem de erro para o usuário, informando sobre a falha no armazenamento dos dados e oferecendo opções de resolução.
c. O usuário pode optar por tentar armazenar os dados novamente ou entrar em contato com o suporte técnico para assistência adicional.
Dependendo da ação tomada pelo usuário, o caso de uso pode ser retomado a partir do passo 4 do fluxo principal (se o usuário optar por tentar novamente) ou ser encerrado (se o usuário optar por entrar em contato com o suporte técnico ou realizar outra ação).
