### ISSUE TITLE
Diagramas de Sequência - Registro de Faltas

### ISSUE THREAD

**Issue by maiarasousa** [maiarasousa/ppads-project#26]

**Comment by Susane-Souza** [comment]
[Diagrama de sequencia Realizar chamada Fluxo principal e Fluxo Alternativo.pdf](https://github.com/maiarasousa/ppads-project/files/14593673/Diagrama.de.sequencia.Realizar.chamada.Fluxo.principal.e.Fluxo.Alternativo.pdf)
