### ISSUE TITLE
Diagramas de Sequência - Notificações de Faltas Excessivas

### ISSUE THREAD

**Issue by maiarasousa** [maiarasousa/ppads-project#34]

**Comment by maiarasousa** [comment]
Finalizado

**Comment by Susane-Souza** [comment]
[Diagrama de sequencia Emitir notificação fluxo principal e alternativo.pdf](https://github.com/maiarasousa/ppads-project/files/14593654/Diagrama.de.sequencia.Emitir.notificacao.fluxo.principal.e.alternativo.pdf)
